apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: $PROVIDER_NAME
  labels:
    app: webhook-server
    provider: $PROVIDER_NAME
spec:
  selector:
    app: webhook-server
  ports:
    - port: 443
      targetPort: webhook-api
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: $PROVIDER_NAME
  labels:
    app: webhook
    provider: $PROVIDER_NAME
  annotations:
    cert-manager.io/inject-ca-from: $PROVIDER_NAME/webhook-tls
webhooks:
  - name: webhook-server.$PROVIDER_NAME.svc
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: $PROVIDER_NAME
        namespace: goci
        path: "/validate"
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["$PROVIDER_DOMAIN"]
        resources: ["connections"]
        apiVersions: ["v1"]
